### PR TITLE
Update xstream

### PR DESCRIPTION
**Pull request by Nitive**

### CODE REVIEW

**Comment by Nitive** [comment]
Except duplicate library in bundle I has problem with typescript annotations:
For
```typescript
import xs, { Stream } from 'xstream'

const up$: Stream<any> = keyboard.downs('up')
```
got error:
```
error TS2322: Type 'Stream<ExtendedKeyboardEvent>' is not assignable to type 'Stream<any>'.
  Property '_ils' is protected but type 'Stream<T>' is not a class derived from 'Stream<T>'.
```
This PR fixes it.

**Comment by artfuldev** [comment]
Thanks, does this fix the issue you mentioned?

**Comment by Nitive** [comment]
@artfuldev No, I tryed to find the problem but was not succeed. I will create a separate issue

**Comment by Nitive** [comment]
Created #35

**Pull request merged**
